#JTMS-14
#problem 13.3.py
#Kaleb Alemayehu
#kalemayehu@jacobs-university.de

import csv
import datetime
from os import write

def extract_datetime(row):
    date = row[0].split(".")
    d = int(date[0])
    mn = int(date[1])
    y = int(date[2])

    time = row[1].split(":")
    h = int(time[0])
    m = int(time[1])
    return datetime.datetime(y, mn, d, h, m)

def extract_temp(row):
    t = row[2]
    try:
        return float(t)
    except:
        return None

def extract_temp(row):
    t = row[2]
    try:
        return float(t)
    except:
        return None

def extract_rel_humidity(row):
    rh = row[3]
    try:
        return float(rh)
    except:
        return None
def extract_wind(row):
    w = row[4]
    try:
        return float(w)
    except:
        return None

def extract_wind_dir(row):
    wd = row[5]
    try:
        return float(wd)
    except:
        return None


f = open("w1data.csv", "r")   #this w1data generated by weather1.py by using 03 as mm    
reader  = csv.reader(f)

ffin = open("wdata2.csv", "w")
writer = csv.writer(ffin)

writer.writerow( ('temp', 'humidity', 'wind', 'direction'))
for row in reader:
    if row[2] == "11.03.2008":
        t = extract_datetime(row)
        if not t:
            continue
        temp =extract_temp(row)
        if not temp:
            continue
        h = extract_rel_humidity(row)
        if not h:
            continue
        w = extract_wind(row)
        if not w:
            continue
        wd = extract_wind_dir(row)
        if not wd:
            continue
        writer.writerow(t, temp, h, w, wd)
ffin.close()
f.close()
